// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ_Yt131RcVtNmB3TAEH94oYlfFfitlTE',
    appId: '1:194451123854:web:f04b4c77b29475f7ac63df',
    messagingSenderId: '194451123854',
    projectId: 'flutter-flutterfire-ex03',
    authDomain: 'flutter-flutterfire-ex03.firebaseapp.com',
    storageBucket: 'flutter-flutterfire-ex03.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxYGVx-C-6j18_3mLohg6Pnx1DnOqCJE8',
    appId: '1:194451123854:android:5ab7a7784089f9ddac63df',
    messagingSenderId: '194451123854',
    projectId: 'flutter-flutterfire-ex03',
    storageBucket: 'flutter-flutterfire-ex03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6i39y730zhRrbyUuvtZnOLN9PE0ujXSE',
    appId: '1:194451123854:ios:3a9d90736780a894ac63df',
    messagingSenderId: '194451123854',
    projectId: 'flutter-flutterfire-ex03',
    storageBucket: 'flutter-flutterfire-ex03.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirestoreEx03',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6i39y730zhRrbyUuvtZnOLN9PE0ujXSE',
    appId: '1:194451123854:ios:3a9d90736780a894ac63df',
    messagingSenderId: '194451123854',
    projectId: 'flutter-flutterfire-ex03',
    storageBucket: 'flutter-flutterfire-ex03.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirestoreEx03',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZ_Yt131RcVtNmB3TAEH94oYlfFfitlTE',
    appId: '1:194451123854:web:508c8ed5a26aa9b0ac63df',
    messagingSenderId: '194451123854',
    projectId: 'flutter-flutterfire-ex03',
    authDomain: 'flutter-flutterfire-ex03.firebaseapp.com',
    storageBucket: 'flutter-flutterfire-ex03.firebasestorage.app',
  );
}
